openapi: 3.1.0
info:
  title: API Gestion d'Événements
  version: 1.0.3
  description: >
    API pour gérer les événements, les lieux et les types d'événements.

servers:
  - url: https://api.reny_event/v1
    description: Serveur de production
  - url: http://localhost:3000/v1
    description: Serveur local de développement

paths:
  /evenements:
    post:
      summary: Créer un nouvel événement
      description: >
        Crée un événement avec ses tarifs, types de places et fichiers associés.
        Les types d'événement et types de place doivent exister au préalable.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvenementCreation'
            examples:
              concert_exemple:
                summary: Exemple de création de concert
                value:
                  titre: "Concert Coldplay 2024"
                  description: "Concert exceptionnel de Coldplay avec setlist spécial"
                  date_debut: "2024-07-15T20:00:00Z"
                  date_fin: "2024-07-15T23:30:00Z"
                  type_evenement: "Concert"
                  lieu:
                    nom: "Stade Barea Mahamasina"
                    adresse: "Mahamasina, Antananarivo"
                    ville: "Antananarivo"
                    capacite: 5000
                  tarifs:
                    - type_place: "VIP"
                      prix: 250000
                      nombre_places: 100
                    - type_place: "Standard"
                      prix: 75000
                      nombre_places: 2000
                  fichiers:
                    - nom_fichier: "affiche-coldplay.jpg"
                      type_mime: "image/jpeg"
                      type_fichier: "affiche"
                      donnees_base64: "/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCdABmX/9k="
      responses:
        '201':
          description: Événement créé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                    example: "e7b8c2f1-1234-4c1a-8b9f-12ef34567890"
                  message:
                    type: string
                    example: "Événement créé avec succès"
        '400':
          description: Données invalides
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Erreur validation titre: Le titre est obligatoire"
        '500':
          description: Erreur interne du serveur

components:
  schemas:
    EvenementCreation:
      type: object
      required:
        - titre
        - date_debut
        - date_fin
        - type_evenement
        - lieu
        - tarifs
      properties:
        titre:
          type: string
          maxLength: 150
          example: "Concert Coldplay 2024"
          description: "Titre de l'événement"
        description:
          type: string
          example: "Concert exceptionnel de Coldplay avec setlist spécial"
          description: "Description détaillée de l'événement"
        date_debut:
          type: string
          format: date-time
          example: "2024-07-15T20:00:00Z"
          description: "Date et heure de début (format ISO 8601)"
        date_fin:
          type: string
          format: date-time
          example: "2024-07-15T23:30:00Z"
          description: "Date et heure de fin (format ISO 8601)"
        type_evenement:
          type: string
          example: "Concert"
          description: "Nom du type d'événement (doit exister au préalable)"
        lieu:
          $ref: '#/components/schemas/LieuCreation'
        tarifs:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/TarifCreation'
          description: "Liste des tarifs proposés pour cet événement"
        fichiers:
          type: array
          items:
            $ref: '#/components/schemas/FichierCreation'
          description: "Fichiers associés à l'événement (optionnel)"

    LieuCreation:
      type: object
      required:
        - nom
        - adresse
        - ville
        - capacite
      properties:
        nom:
          type: string
          maxLength: 150
          example: "Stade Barea Mahamasina"
        adresse:
          type: string
          example: "Mahamasina, Antananarivo"
        ville:
          type: string
          maxLength: 100
          example: "Antananarivo"
        capacite:
          type: integer
          minimum: 1
          example: 5000

    TarifCreation:
      type: object
      required:
        - type_place
        - prix
        - nombre_places
      properties:
        type_place:
          type: string
          example: "VIP"
          description: "Nom du type de place (doit exister au préalable)"
        prix:
          type: number
          format: float
          minimum: 0
          example: 250000
        nombre_places:
          type: integer
          minimum: 1
          example: 100

    FichierCreation:
      type: object
      required:
        - nom_fichier
        - type_mime
        - type_fichier
        - donnees_base64
      properties:
        nom_fichier:
          type: string
          maxLength: 255
          example: "affiche-coldplay.jpg"
        type_mime:
          type: string
          example: "image/jpeg"
        type_fichier:
          type: string
          enum: [photo, affiche, document]
          example: "affiche"
        donnees_base64:
          type: string
          description: "Fichier encodé en base64"
          example: "/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCdABmX/9k="